### ISSUE TITLE
Question about configuration and upstream

### ISSUE THREAD

**Issue by NeekoDev** [eugene-khyst/letsencrypt-docker-compose#61]
Hi! First of all, thank you very much for this tool, I'm new to Docker and it's very enriching and it works perfectly as I wanted! 😃 

I would just like to understand better this part of the documentation : 

https://github.com/eugene-khyst/letsencrypt-docker-compose#2-3-2-2

---
I have a Nuxt 3 application in the example folder : `/home/docker/letsencrypt-docker-compose/examples/docker-nuxt`
With a **docker-compose.yml** file. 

But should I still add this (see below) in the **docker-compose.yml** at the root (`/home/docker/letsencrypt-docker-compose`) : 

```yml
services:
  docker-nuxt:
    build: ./examples/docker-nuxt
    image: docker-nuxt
    restart: unless-stopped
```

Or do I just need to edit the docker-compose.yml from the example app with this (and remove above conf) : 

```yml
version: "3"

services:
  docker-nuxt:
    build: ./examples/docker-nuxt
    image: docker-nuxt
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

networks:
  letsencrypt-docker-compose:
    name: letsencrypt-docker-compose_default
    external: true
```

It's just a little confusing for me 😸 
Thanks!
